import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/app/globals.css';
import { Header } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
  weight: '100 900',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={pretendard.variable}>
      <body>
        <Header isLoggedIn={false} />
        <main className='pt-[var(--header-height)]'>{children}</main>
      </body>
    </html>
  );
}
